-- @description FX Permutator
-- @version 1.1.0
-- @changelog
--   HiDPI/Retina support
--   AU plugin support
--   Plugin priority option
--   Usability improvements
--   Performance optimization
-- @author Tech Audio
-- @metapackage
-- @provides
--   [main] TA_FX Permutator.luac > TA_FX Permutator.lua
