-- @about
--   # XY Pad is super cool!
--
--   We all know this, but should probably explain how.
-- @description TechAudio XY Pad
-- @link https://techaud.io
-- @link https://github.com/TeamAudio
-- @version 1.0
-- @author techaudio
-- @changelog
--   Initial release
-- @provides
--   [nomain] .
--   [main] xypad/TA_XY Pad.lua
--   [main] xypad/TA_XY Set X.lua
--   [main] xypad/TA_XY Set Y.lua
--   [lua] xypad/config.lua
--   [lua] xypad/dkjson.lua
--   [lua] xypad/extstate.lua
--   [lua] xypad/fonts.lua
--   [lua] xypad/logging.lua
--   [lua] xypad/mappings.lua
--   [lua] xypad/path_history.lua
--   [lua] xypad/paths.lua
--   [lua] xypad/storage.lua
--   [lua] xypad/ui.lua

